import { Pool } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-serverless";
import { movies } from "../shared/schema";
import type { InsertMovie } from "../shared/schema";

const posterImages = [
  "/stock_images/movie_posters_cinema_b756243f.jpg",
  "/stock_images/movie_posters_cinema_75250d57.jpg",
  "/stock_images/movie_posters_cinema_778365f7.jpg",
  "/stock_images/movie_posters_cinema_a5acc9c4.jpg",
  "/stock_images/movie_posters_cinema_d7839bfc.jpg",
  "/stock_images/movie_posters_cinema_add6a7b1.jpg",
  "/stock_images/movie_posters_cinema_fc92f6b8.jpg",
  "/stock_images/movie_posters_cinema_83b0bd8b.jpg",
  "/stock_images/movie_posters_cinema_6f487265.jpg",
  "/stock_images/movie_posters_cinema_d77135fd.jpg",
];

const backdropImages = [
  "/stock_images/cinematic_movie_back_8b328122.jpg",
  "/stock_images/cinematic_movie_back_8efabebc.jpg",
  "/stock_images/cinematic_movie_back_cb8365da.jpg",
  "/stock_images/cinematic_movie_back_c0d2c297.jpg",
  "/stock_images/cinematic_movie_back_e511678a.jpg",
  "/stock_images/cinematic_movie_back_484f26eb.jpg",
  "/stock_images/cinematic_movie_back_23be849c.jpg",
  "/stock_images/cinematic_movie_back_5a6a0634.jpg",
  "/stock_images/cinematic_movie_back_bcb8d77e.jpg",
  "/stock_images/cinematic_movie_back_0e2dc317.jpg",
];

const newMovies: InsertMovie[] = [
  {
    title: "Eternal Horizon",
    description: "A visionary explorer journeys to the edge of the known universe, discovering ancient civilizations and cosmic secrets that challenge humanity's understanding of existence.",
    rating: "8.8",
    year: 2023,
    duration: "2h 35m",
    genres: ["Sci-Fi", "Adventure", "Mystery"],
    cast: ["Chris Pratt", "Zoe Saldana", "Chiwetel Ejiofor", "Gal Gadot"],
    director: "James Cameron",
    posterImage: posterImages[0],
    backdropImage: backdropImages[0],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Last Guardian",
    description: "In a post-apocalyptic world, a lone warrior protects the last remaining sanctuary from marauding forces while searching for a cure to save humanity.",
    rating: "8.3",
    year: 2024,
    duration: "2h 18m",
    genres: ["Action", "Drama", "Sci-Fi"],
    cast: ["Tom Hardy", "Charlize Theron", "Oscar Isaac", "Danai Gurira"],
    director: "George Miller",
    posterImage: posterImages[1],
    backdropImage: backdropImages[1],
    isTrending: 1,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Midnight in Venice",
    description: "A troubled artist finds inspiration and love in the mysterious canals of Venice, but dark secrets from the past threaten to destroy everything.",
    rating: "7.9",
    year: 2024,
    duration: "1h 58m",
    genres: ["Romance", "Drama", "Mystery"],
    cast: ["Adam Driver", "Saoirse Ronan", "Javier Bardem", "Marion Cotillard"],
    director: "Luca Guadagnino",
    posterImage: posterImages[2],
    backdropImage: backdropImages[2],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Code Zero",
    description: "An elite hacker is recruited by the FBI to stop a cyber terrorist from launching a devastating attack that could cripple the world's infrastructure.",
    rating: "8.1",
    year: 2023,
    duration: "2h 5m",
    genres: ["Thriller", "Action", "Crime"],
    cast: ["Rami Malek", "Jessica Chastain", "Mahershala Ali", "Sandra Oh"],
    director: "Kathryn Bigelow",
    posterImage: posterImages[3],
    backdropImage: backdropImages[3],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Painted Sky",
    description: "A young painter in 1920s Paris discovers her work can bring paintings to life, but this gift attracts dangerous admirers seeking to exploit her power.",
    rating: "8.5",
    year: 2024,
    duration: "2h 12m",
    genres: ["Fantasy", "Drama", "Romance"],
    cast: ["Florence Pugh", "Timothée Chalamet", "Ralph Fiennes", "Léa Seydoux"],
    director: "Guillermo del Toro",
    posterImage: posterImages[4],
    backdropImage: backdropImages[4],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Iron Will",
    description: "A championship boxer fights his way back from a career-ending injury, facing both physical and emotional battles to reclaim his title and dignity.",
    rating: "7.7",
    year: 2023,
    duration: "2h 8m",
    genres: ["Sports", "Drama"],
    cast: ["Michael B. Jordan", "Sylvester Stallone", "Tessa Thompson", "Jonathan Majors"],
    director: "Ryan Coogler",
    posterImage: posterImages[5],
    backdropImage: backdropImages[5],
    isTrending: 0,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Silence Between Us",
    description: "Two strangers connected by grief form an unlikely friendship through letters, discovering healing and hope in the most unexpected places.",
    rating: "8.4",
    year: 2024,
    duration: "1h 52m",
    genres: ["Drama", "Romance"],
    cast: ["Andrew Garfield", "Carey Mulligan", "Brian Tyree Henry", "Lupita Nyong'o"],
    director: "Chloe Zhao",
    posterImage: posterImages[6],
    backdropImage: backdropImages[6],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Neon Nights",
    description: "In a cyberpunk metropolis, a detective and a rogue AI must team up to solve a series of impossible murders that could tear reality apart.",
    rating: "8.6",
    year: 2023,
    duration: "2h 28m",
    genres: ["Sci-Fi", "Thriller", "Mystery"],
    cast: ["Ryan Gosling", "Ana de Armas", "Keanu Reeves", "Hiroyuki Sanada"],
    director: "Ridley Scott",
    posterImage: posterImages[7],
    backdropImage: backdropImages[7],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Comedy King",
    description: "A stand-up comedian's meteoric rise to fame is threatened when scandals from his past resurface, forcing him to confront who he really is.",
    rating: "7.6",
    year: 2024,
    duration: "1h 48m",
    genres: ["Comedy", "Drama"],
    cast: ["Adam Sandler", "Jennifer Aniston", "Kevin Hart", "Mindy Kaling"],
    director: "Judd Apatow",
    posterImage: posterImages[8],
    backdropImage: backdropImages[8],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Whispers in the Dark",
    description: "A paranormal investigator explores a haunted asylum where patients claim to see visions of the future, only to discover the terrifying truth behind the prophecies.",
    rating: "7.8",
    year: 2024,
    duration: "2h 2m",
    genres: ["Horror", "Mystery", "Thriller"],
    cast: ["James McAvoy", "Anya Taylor-Joy", "Jeffrey Dean Morgan", "Vera Farmiga"],
    director: "Mike Flanagan",
    posterImage: posterImages[9],
    backdropImage: backdropImages[9],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Rising Thunder",
    description: "An underdog race car driver defies all odds to compete in the world's most dangerous racing championship, risking everything for glory.",
    rating: "7.9",
    year: 2023,
    duration: "2h 15m",
    genres: ["Action", "Sports", "Drama"],
    cast: ["Daniel Ricciardo", "Daisy Edgar-Jones", "Idris Elba", "Emilia Clarke"],
    director: "Ron Howard",
    posterImage: posterImages[0],
    backdropImage: backdropImages[0],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Forgotten Kingdom",
    description: "Archaeologists discover a lost civilization beneath the Amazon rainforest, unleashing ancient powers that could reshape the modern world.",
    rating: "8.2",
    year: 2024,
    duration: "2h 22m",
    genres: ["Adventure", "Fantasy", "Action"],
    cast: ["Chris Hemsworth", "Tessa Thompson", "Antonio Banderas", "Michelle Yeoh"],
    director: "Steven Spielberg",
    posterImage: posterImages[1],
    backdropImage: backdropImages[1],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Echoes of Tomorrow",
    description: "A physicist discovers a way to send messages to the past, but each alteration creates devastating ripple effects in the present.",
    rating: "8.7",
    year: 2023,
    duration: "2h 18m",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    cast: ["Benedict Cumberbatch", "Emily Blunt", "Dev Patel", "Tilda Swinton"],
    director: "Christopher Nolan",
    posterImage: posterImages[2],
    backdropImage: backdropImages[2],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Crimson Tide",
    description: "A naval officer must make impossible decisions during a submarine crisis that could trigger World War III.",
    rating: "8.0",
    year: 2024,
    duration: "2h 8m",
    genres: ["Action", "Thriller", "War"],
    cast: ["Tom Cruise", "Rebecca Ferguson", "Jon Bernthal", "Gugu Mbatha-Raw"],
    director: "Tony Scott",
    posterImage: posterImages[3],
    backdropImage: backdropImages[3],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Summer of Dreams",
    description: "Three childhood friends reunite for one last summer adventure before life takes them in different directions, rediscovering what truly matters.",
    rating: "7.5",
    year: 2024,
    duration: "1h 55m",
    genres: ["Drama", "Comedy", "Romance"],
    cast: ["Jacob Elordi", "Sydney Sweeney", "Harris Dickinson", "Mia Goth"],
    director: "Richard Linklater",
    posterImage: posterImages[4],
    backdropImage: backdropImages[4],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Constellation",
    description: "An astronaut stranded in deep space discovers she's not alone when mysterious signals lead her to an impossible discovery.",
    rating: "8.4",
    year: 2023,
    duration: "2h 12m",
    genres: ["Sci-Fi", "Mystery", "Thriller"],
    cast: ["Natalie Portman", "Oscar Isaac", "Adam Driver", "Alicia Vikander"],
    director: "Alex Garland",
    posterImage: posterImages[5],
    backdropImage: backdropImages[5],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Beneath the Surface",
    description: "A deep-sea exploration team encounters prehistoric creatures thought to be extinct, fighting for survival in the ocean's darkest depths.",
    rating: "7.7",
    year: 2024,
    duration: "1h 58m",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    cast: ["Jason Statham", "Ruby Rose", "Rainn Wilson", "Sophia Cai"],
    director: "Jon Turteltaub",
    posterImage: posterImages[6],
    backdropImage: backdropImages[6],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Phoenix Protocol",
    description: "A secret government program creates super-soldiers, but when one goes rogue, a special agent must stop him before he destroys everything.",
    rating: "8.1",
    year: 2023,
    duration: "2h 25m",
    genres: ["Action", "Sci-Fi", "Thriller"],
    cast: ["Henry Cavill", "Margot Robbie", "John David Washington", "Letitia Wright"],
    director: "Matt Reeves",
    posterImage: posterImages[7],
    backdropImage: backdropImages[7],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Laugh Lines",
    description: "A struggling comedy writer's life turns upside down when his fictional sitcom characters start appearing in real life.",
    rating: "7.4",
    year: 2024,
    duration: "1h 42m",
    genres: ["Comedy", "Fantasy"],
    cast: ["Paul Rudd", "Kristen Wiig", "Bill Hader", "Maya Rudolph"],
    director: "Shawn Levy",
    posterImage: posterImages[8],
    backdropImage: backdropImages[8],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Haunting Hour",
    description: "A group of paranormal enthusiasts spend the night in the world's most haunted location, but they're not prepared for what they awaken.",
    rating: "7.6",
    year: 2024,
    duration: "1h 52m",
    genres: ["Horror", "Thriller"],
    cast: ["Taissa Farmiga", "Patrick Wilson", "Vera Farmiga", "Madison Iseman"],
    director: "James Wan",
    posterImage: posterImages[9],
    backdropImage: backdropImages[9],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Velocity",
    description: "A getaway driver with exceptional skills is forced out of retirement for one last impossible heist that could set him free forever.",
    rating: "8.2",
    year: 2023,
    duration: "2h 5m",
    genres: ["Action", "Crime", "Thriller"],
    cast: ["Ryan Reynolds", "Charlize Theron", "Idris Elba", "Zazie Beetz"],
    director: "David Leitch",
    posterImage: posterImages[0],
    backdropImage: backdropImages[0],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Dragon's Pearl",
    description: "In ancient China, a young warrior must retrieve a mystical pearl to save his kingdom from a powerful sorcerer's dark magic.",
    rating: "8.3",
    year: 2024,
    duration: "2h 18m",
    genres: ["Fantasy", "Adventure", "Action"],
    cast: ["Simu Liu", "Awkwafina", "Tony Leung", "Michelle Yeoh"],
    director: "Ang Lee",
    posterImage: posterImages[1],
    backdropImage: backdropImages[1],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Quantum Leap",
    description: "Scientists accidentally open a portal to parallel dimensions, and now they must close it before reality itself collapses.",
    rating: "8.5",
    year: 2023,
    duration: "2h 32m",
    genres: ["Sci-Fi", "Thriller", "Adventure"],
    cast: ["Tom Holland", "Zendaya", "Jake Gyllenhaal", "Benedict Wong"],
    director: "Denis Villeneuve",
    posterImage: posterImages[2],
    backdropImage: backdropImages[2],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Silent Witness",
    description: "A deaf forensic expert uses her unique perspective to solve crimes that others miss, but her latest case puts her own life in danger.",
    rating: "8.0",
    year: 2024,
    duration: "2h 2m",
    genres: ["Crime", "Thriller", "Drama"],
    cast: ["Millicent Simmonds", "John Krasinski", "Cillian Murphy", "Djimon Hounsou"],
    director: "John Krasinski",
    posterImage: posterImages[3],
    backdropImage: backdropImages[3],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Hearts in Bloom",
    description: "A florist and a wedding planner fall in love while organizing the wedding of the century, but their own fears threaten their happiness.",
    rating: "7.8",
    year: 2024,
    duration: "1h 48m",
    genres: ["Romance", "Comedy"],
    cast: ["Ana de Armas", "Chris Evans", "Mindy Kaling", "Kumail Nanjiani"],
    director: "Nancy Meyers",
    posterImage: posterImages[4],
    backdropImage: backdropImages[4],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Final Frontier",
    description: "Humanity's first interstellar colony ship encounters an alien signal that leads them to a revelation about the universe's true nature.",
    rating: "8.9",
    year: 2023,
    duration: "2h 45m",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    director: "Christopher Nolan",
    posterImage: posterImages[5],
    backdropImage: backdropImages[5],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Shadows and Echoes",
    description: "A photographer captures images of crimes before they happen, racing against time to prevent murders while becoming the prime suspect.",
    rating: "7.9",
    year: 2024,
    duration: "2h 8m",
    genres: ["Thriller", "Mystery", "Crime"],
    cast: ["Jake Gyllenhaal", "Amy Adams", "Hugh Jackman", "Paul Dano"],
    director: "David Fincher",
    posterImage: posterImages[6],
    backdropImage: backdropImages[6],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Reef",
    description: "Marine biologists discover an underwater civilization, but their presence threatens to expose both worlds to catastrophic consequences.",
    rating: "8.1",
    year: 2023,
    duration: "2h 15m",
    genres: ["Adventure", "Fantasy", "Sci-Fi"],
    cast: ["Jason Momoa", "Amber Heard", "Willem Dafoe", "Nicole Kidman"],
    director: "James Wan",
    posterImage: posterImages[7],
    backdropImage: backdropImages[7],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Comedy Central",
    description: "A legendary comedy club faces closure, and the performers must put on the show of their lives to save their second home.",
    rating: "7.3",
    year: 2024,
    duration: "1h 52m",
    genres: ["Comedy", "Drama"],
    cast: ["Jerry Seinfeld", "Amy Schumer", "Dave Chappelle", "Ali Wong"],
    director: "Edgar Wright",
    posterImage: posterImages[8],
    backdropImage: backdropImages[8],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Curse of Hollow Hill",
    description: "A family moves into a Victorian mansion, unaware that it sits on an ancient burial ground where malevolent spirits seek revenge.",
    rating: "7.7",
    year: 2024,
    duration: "1h 58m",
    genres: ["Horror", "Mystery"],
    cast: ["Patrick Wilson", "Vera Farmiga", "Annabelle Wallis", "Madison Iseman"],
    director: "James Wan",
    posterImage: posterImages[9],
    backdropImage: backdropImages[9],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Street Kings",
    description: "An undercover cop infiltrates a powerful crime syndicate, but the deeper he goes, the harder it becomes to remember which side he's on.",
    rating: "8.2",
    year: 2023,
    duration: "2h 12m",
    genres: ["Crime", "Action", "Thriller"],
    cast: ["Leonardo DiCaprio", "Mark Wahlberg", "Matt Damon", "Jack Nicholson"],
    director: "Martin Scorsese",
    posterImage: posterImages[0],
    backdropImage: backdropImages[0],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Enchanted Forest",
    description: "A young girl discovers a magical forest where fairy tales come to life, but an ancient evil threatens to consume both worlds.",
    rating: "8.0",
    year: 2024,
    duration: "2h 5m",
    genres: ["Fantasy", "Adventure", "Family"],
    cast: ["Millie Bobby Brown", "Tom Holland", "Ian McKellen", "Cate Blanchett"],
    director: "Guillermo del Toro",
    posterImage: posterImages[1],
    backdropImage: backdropImages[1],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Parallel Lives",
    description: "A neuroscientist discovers technology that allows people to experience alternate versions of their lives, but some choices can't be undone.",
    rating: "8.6",
    year: 2023,
    duration: "2h 28m",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    cast: ["Oscar Isaac", "Kirsten Dunst", "Michael Shannon", "Greta Lee"],
    director: "Charlie Kaufman",
    posterImage: posterImages[2],
    backdropImage: backdropImages[2],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Thunder Road",
    description: "A motorcycle gang's peaceful existence is shattered when a rival gang threatens their territory, forcing them into an all-out war.",
    rating: "7.8",
    year: 2024,
    duration: "2h 8m",
    genres: ["Action", "Drama", "Crime"],
    cast: ["Charlie Hunnam", "Ron Perlman", "Katey Sagal", "Maggie Siff"],
    director: "Kurt Sutter",
    posterImage: posterImages[3],
    backdropImage: backdropImages[3],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Love in Translation",
    description: "An interpreter falls for a diplomat who speaks a language she doesn't know, forcing them to find new ways to communicate their feelings.",
    rating: "7.9",
    year: 2024,
    duration: "1h 55m",
    genres: ["Romance", "Comedy", "Drama"],
    cast: ["Gemma Chan", "Henry Golding", "Constance Wu", "Michelle Yeoh"],
    director: "Jon M. Chu",
    posterImage: posterImages[4],
    backdropImage: backdropImages[4],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Beyond the Stars",
    description: "An astronaut returns from a decade-long mission to find Earth has evolved beyond recognition, and she must adapt to a world that no longer needs her.",
    rating: "8.4",
    year: 2023,
    duration: "2h 22m",
    genres: ["Sci-Fi", "Drama"],
    cast: ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "Jude Law"],
    director: "Anna Boden",
    posterImage: posterImages[5],
    backdropImage: backdropImages[5],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Vanishing",
    description: "People are disappearing from a small town with no explanation, and a journalist's investigation reveals a conspiracy that goes deeper than anyone imagined.",
    rating: "8.0",
    year: 2024,
    duration: "2h 2m",
    genres: ["Mystery", "Thriller", "Drama"],
    cast: ["Rooney Mara", "Daniel Craig", "Stellan Skarsgård", "Jodie Foster"],
    director: "David Fincher",
    posterImage: posterImages[6],
    backdropImage: backdropImages[6],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Ocean's Revenge",
    description: "A master thief assembles a new crew to pull off an impossible heist against the crime lord who betrayed them years ago.",
    rating: "8.1",
    year: 2023,
    duration: "2h 18m",
    genres: ["Crime", "Thriller", "Action"],
    cast: ["Brad Pitt", "George Clooney", "Matt Damon", "Julia Roberts"],
    director: "Steven Soderbergh",
    posterImage: posterImages[7],
    backdropImage: backdropImages[7],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Joke's On You",
    description: "A prankster's elaborate practical jokes spiral out of control when one of them goes viral, changing his life and relationships forever.",
    rating: "7.2",
    year: 2024,
    duration: "1h 42m",
    genres: ["Comedy"],
    cast: ["Will Ferrell", "John C. Reilly", "Steve Carell", "Tina Fey"],
    director: "Adam McKay",
    posterImage: posterImages[8],
    backdropImage: backdropImages[8],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Séance",
    description: "A skeptical medium is forced to confront her beliefs when real spirits begin to communicate through her, revealing dark secrets.",
    rating: "7.5",
    year: 2024,
    duration: "1h 52m",
    genres: ["Horror", "Mystery", "Thriller"],
    cast: ["Sarah Paulson", "Lily Rabe", "Evan Peters", "Jessica Lange"],
    director: "Mike Flanagan",
    posterImage: posterImages[9],
    backdropImage: backdropImages[9],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Blitz",
    description: "During World War II London, a bomb disposal expert races against time to defuse a series of deadly devices while the city burns around him.",
    rating: "8.3",
    year: 2023,
    duration: "2h 15m",
    genres: ["War", "Thriller", "Drama"],
    cast: ["Cillian Murphy", "Emily Blunt", "Kenneth Branagh", "Mark Rylance"],
    director: "Christopher Nolan",
    posterImage: posterImages[0],
    backdropImage: backdropImages[0],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Enchanted Crown",
    description: "A humble blacksmith discovers he's the rightful heir to a magical kingdom and must reclaim his throne from a tyrannical usurper.",
    rating: "7.9",
    year: 2024,
    duration: "2h 12m",
    genres: ["Fantasy", "Adventure", "Action"],
    cast: ["Tom Holland", "Daisy Ridley", "Mark Ruffalo", "Cate Blanchett"],
    director: "Peter Jackson",
    posterImage: posterImages[1],
    backdropImage: backdropImages[1],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Time Fracture",
    description: "A temporal anomaly allows a grieving scientist to revisit moments from the past, but changing history comes with unforeseen consequences.",
    rating: "8.7",
    year: 2023,
    duration: "2h 35m",
    genres: ["Sci-Fi", "Drama", "Thriller"],
    cast: ["Hugh Jackman", "Rachel McAdams", "Ethan Hawke", "Saoirse Ronan"],
    director: "Denis Villeneuve",
    posterImage: posterImages[2],
    backdropImage: backdropImages[2],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Mercenary",
    description: "A hired gun with a strict moral code takes on one last job to protect a young witness, becoming the only thing standing between her and certain death.",
    rating: "8.0",
    year: 2024,
    duration: "2h 5m",
    genres: ["Action", "Thriller", "Crime"],
    cast: ["Keanu Reeves", "Halle Berry", "Laurence Fishburne", "Ian McShane"],
    director: "Chad Stahelski",
    posterImage: posterImages[3],
    backdropImage: backdropImages[3],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Paris in Spring",
    description: "A chef and a food critic fall in love during Paris Fashion Week, but their competitive natures threaten to tear them apart.",
    rating: "7.7",
    year: 2024,
    duration: "1h 52m",
    genres: ["Romance", "Comedy", "Drama"],
    cast: ["Emma Stone", "Ryan Gosling", "Marion Cotillard", "Omar Sy"],
    director: "Woody Allen",
    posterImage: posterImages[4],
    backdropImage: backdropImages[4],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Cosmic Dawn",
    description: "The first humans born in space must decide humanity's future when they discover evidence of intelligent alien life.",
    rating: "8.5",
    year: 2023,
    duration: "2h 28m",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    cast: ["Zendaya", "Tom Holland", "John Boyega", "Daisy Ridley"],
    director: "Alfonso Cuarón",
    posterImage: posterImages[5],
    backdropImage: backdropImages[5],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "The Cipher",
    description: "A cryptographer is recruited to decode a mysterious message that could prevent a global catastrophe, but the solution may be worse than the problem.",
    rating: "8.2",
    year: 2024,
    duration: "2h 8m",
    genres: ["Thriller", "Mystery", "Drama"],
    cast: ["Benedict Cumberbatch", "Keira Knightley", "Matthew Goode", "Allen Leech"],
    director: "Morten Tyldum",
    posterImage: posterImages[6],
    backdropImage: backdropImages[6],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "Deep Blue",
    description: "A submarine crew discovers an underwater trench that leads to a prehistoric world, but escaping becomes their greatest challenge.",
    rating: "7.8",
    year: 2023,
    duration: "2h 2m",
    genres: ["Adventure", "Sci-Fi", "Thriller"],
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "Stephen Lang"],
    director: "James Cameron",
    posterImage: posterImages[7],
    backdropImage: backdropImages[7],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
  {
    title: "Punchline",
    description: "A comedy duo's friendship is tested when one becomes famous while the other struggles, forcing them to confront jealousy and loyalty.",
    rating: "7.4",
    year: 2024,
    duration: "1h 48m",
    genres: ["Comedy", "Drama"],
    cast: ["Seth Rogen", "James Franco", "Jonah Hill", "Danny McBride"],
    director: "Judd Apatow",
    posterImage: posterImages[8],
    backdropImage: backdropImages[8],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Possession",
    description: "An antique music box unleashes a malevolent demon that possesses a young girl, and her father must find a way to save her soul.",
    rating: "7.6",
    year: 2024,
    duration: "1h 55m",
    genres: ["Horror", "Thriller"],
    cast: ["Jeffrey Dean Morgan", "Kyra Sedgwick", "Natasha Calis", "Madison Davenport"],
    director: "Sam Raimi",
    posterImage: posterImages[9],
    backdropImage: backdropImages[9],
    isTrending: 0,
    isNewAndPopular: 1,
    isHeroBanner: 0,
  },
  {
    title: "The Underworld",
    description: "A journalist goes undercover in the criminal underworld to expose corruption, but soon realizes she's in too deep to escape.",
    rating: "8.1",
    year: 2023,
    duration: "2h 12m",
    genres: ["Crime", "Thriller", "Drama"],
    cast: ["Carey Mulligan", "Andy Serkis", "John Goodman", "Helena Bonham Carter"],
    director: "Paul Greengrass",
    posterImage: posterImages[0],
    backdropImage: backdropImages[0],
    isTrending: 1,
    isNewAndPopular: 0,
    isHeroBanner: 0,
  },
];

async function addMovies() {
  if (!process.env.DATABASE_URL) {
    console.error("DATABASE_URL not found. This script requires a PostgreSQL database.");
    process.exit(1);
  }

  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool);

  console.log(`Adding ${newMovies.length} movies to the database...`);

  try {
    for (const movie of newMovies) {
      await db.insert(movies).values(movie);
      console.log(`✓ Added: ${movie.title}`);
    }

    console.log(`\n🎉 Successfully added ${newMovies.length} movies!`);
  } catch (error) {
    console.error("Error adding movies:", error);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

addMovies();
